### ISSUE TITLE
No matching version found for @jsenv/url-meta@6.0.0.

### ISSUE THREAD

**Issue by cuixiaorui** [jsenv/url-meta#9]
hi 
When I was installing the @jsenv/url-meta library

NPM hint I
```shell
npm i @jsenv/url-meta                                                         
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @jsenv/url-meta@6.0.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

yarn  has also advised me that V6.0.0 is not available

What should I do?

**Comment by dmail** [comment]
I don't know how I could miss your issue, sorry for the delay.

This package is on npm, I use it in many places and it's visible at https://www.npmjs.com/package/@jsenv/url-meta/v/6.0.0.
What is your npm version?
